repos:
  - gh-action-extract-branch-name
  # - keptn-on-keptn
  - gh-action-send-event
  - gh-action-build-docker-image
  - gh-action-ci-prepare-keptn-cluster

approvers: []

maintainers:
#  - grabnerandi
#  - agardnerIT
  - aepfli-test

admins: []
